# Generated by Django 6.0.3 on 2026-03-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('rx', 'Receiver (Rx)'), ('sx', 'Source (Sx)')], max_length=2)),
                ('datum', models.CharField(choices=[('mga2020', 'MGA2020'), ('mga94', 'MGA94')], max_length=10)),
                ('zone', models.CharField(choices=[('46', 'Zone 46'), ('47', 'Zone 47'), ('48', 'Zone 48'), ('49', 'Zone 49'), ('50', 'Zone 50'), ('51', 'Zone 51'), ('52', 'Zone 52'), ('53', 'Zone 53'), ('54', 'Zone 54'), ('55', 'Zone 55'), ('56', 'Zone 56'), ('57', 'Zone 57')], max_length=2)),
                ('file', models.FileField(upload_to='survey_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_files', to='reports.job')),
            ],
        ),
    ]
