# Generated by Django 6.0.3 on 2026-03-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_surveyfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rx_interval',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Receiver Interval (m)'),
        ),
        migrations.AddField(
            model_name='job',
            name='sx_interval',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Source Interval (m)'),
        ),
    ]
