# Generated by Django 6.0.3 on 2026-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_job_rx_interval_job_sx_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='observer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='operators',
            field=models.TextField(blank=True, help_text='One operator per line'),
        ),
    ]
