# Generated by Django 6.0.3 on 2026-03-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dailyreport_observer_dailyreport_operators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='observer',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='operators',
        ),
        migrations.AddField(
            model_name='job',
            name='observer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='operators',
            field=models.TextField(blank=True, help_text='One operator per line'),
        ),
    ]
