# Generated by Django 6.0.3 on 2026-03-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_dailyreport_observer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='observer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='operators',
        ),
    ]
