# Generated by Django 6.0.3 on 2026-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_job_observer_remove_job_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='observer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='operators',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PersonnelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('observer', 'Observer'), ('operator', 'Vibe Operator')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'role')},
            },
        ),
    ]
