# Generated by Django 6.0.3 on 2026-03-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dailyreport_observer_dailyreport_operators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='observer',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='observers',
            field=models.TextField(blank=True),
        ),
    ]
