# Generated by Django 6.0.3 on 2026-03-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_dailyreport_observer_dailyreport_observers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('zip', 'Zip Archive'), ('obslog', 'Obs Log'), ('pss', 'PSS'), ('cog', 'COG'), ('rx_deployment', 'Receiver Deployment')], max_length=20)),
                ('file', models.FileField(upload_to='report_files/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.dailyreport')),
            ],
        ),
    ]
