# Generated by Django 6.0.3 on 2026-03-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reportfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('category', models.CharField(choices=[('record', 'Record'), ('vib_movements', 'Vib Movements'), ('toolbox', 'Toolbox/Safety Meetings'), ('setup', 'Setup Equipment'), ('site_fam', 'Site Familiarization'), ('layout', '1st Layout after Mobilisation'), ('pickup', 'Pickup for Demobilisation'), ('recorder_move', 'Recorder Move'), ('node_deploy', 'Node Deployment'), ('washdown', 'Washdown'), ('inductions', 'Inductions'), ('travel', 'Daily Travel'), ('standby', 'Standby Other'), ('other', 'Other')], max_length=50)),
                ('activity_type', models.CharField(choices=[('work', 'Work'), ('standby', 'Standby'), ('downtime', 'Downtime'), ('travel', 'Travel'), ('rdo', 'RDO'), ('mob', 'Mob/Demob')], default='work', max_length=20)),
                ('details', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reports.dailyreport')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
    ]
