# Generated by Django 6.0.3 on 2026-03-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
