# Generated by Django 6.0.3 on 2026-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_activitycategory_alter_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='diary',
            field=models.TextField(blank=True),
        ),
    ]
