# Generated by Django 6.0.3 on 2026-03-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_dailyreport_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estimated_rx_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Rx Count'),
        ),
        migrations.AddField(
            model_name='job',
            name='estimated_sx_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Sx Count'),
        ),
        migrations.AddField(
            model_name='surveyfile',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
