# Generated by Django 6.0.3 on 2026-03-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_survey_final_and_estimated_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pss_force_avg_amber',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_force_avg_green',
            field=models.FloatField(default=55),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_force_max_amber',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_force_max_green',
            field=models.FloatField(default=72),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_phase_avg_amber',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_phase_avg_green',
            field=models.FloatField(default=3.6),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_phase_max_amber',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_phase_max_green',
            field=models.FloatField(default=9),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_thd_avg_amber',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_thd_avg_green',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_thd_max_amber',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='job',
            name='pss_thd_max_green',
            field=models.FloatField(default=45),
        ),
    ]
