# Generated by Django 6.0.3 on 2026-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_job_pss_force_avg_amber_job_pss_force_avg_green_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSSQCPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pss_force_avg_green', models.FloatField(default=55)),
                ('pss_force_avg_amber', models.FloatField(default=50)),
                ('pss_force_max_green', models.FloatField(default=72)),
                ('pss_force_max_amber', models.FloatField(default=70)),
                ('pss_phase_avg_green', models.FloatField(default=3.6)),
                ('pss_phase_avg_amber', models.FloatField(default=4.0)),
                ('pss_phase_max_green', models.FloatField(default=9)),
                ('pss_phase_max_amber', models.FloatField(default=10)),
                ('pss_thd_avg_green', models.FloatField(default=18)),
                ('pss_thd_avg_amber', models.FloatField(default=20)),
                ('pss_thd_max_green', models.FloatField(default=45)),
                ('pss_thd_max_amber', models.FloatField(default=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
