# Generated by Django 6.0.3 on 2026-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_diarytemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfile',
            name='datum',
            field=models.CharField(choices=[('mga2020', 'GDA2020 / MGA2020'), ('itrf2014', 'ITRF2014 / UTM South'), ('mga94', 'GDA94 / MGA94'), ('agd84', 'AGD84 / AMG84'), ('agd66', 'AGD66 / AMG66'), ('wgs84', 'WGS84 / UTM South')], max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyfile',
            name='zone',
            field=models.CharField(choices=[('46', 'Zone 46'), ('47', 'Zone 47'), ('48', 'Zone 48'), ('49', 'Zone 49'), ('50', 'Zone 50'), ('51', 'Zone 51'), ('52', 'Zone 52'), ('53', 'Zone 53'), ('54', 'Zone 54'), ('55', 'Zone 55'), ('56', 'Zone 56'), ('57', 'Zone 57'), ('58', 'Zone 58')], max_length=2),
        ),
    ]
