# Generated by Django 6.0.3 on 2026-03-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_alter_surveyfile_datum_alter_surveyfile_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='map_color_planned',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='job',
            name='map_color_prev',
            field=models.CharField(default='#29b6f6', max_length=7),
        ),
        migrations.AddField(
            model_name='job',
            name='map_color_today',
            field=models.CharField(default='#ff9800', max_length=7),
        ),
    ]
