# Generated by Django 6.0.3 on 2026-03-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_job_supervisor_filename_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hours',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
