# Generated by Django 6.0.3 on 2026-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_activity_notes_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
