# Generated by Django 6.0.3 on 2026-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_activity_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('contractor', 'Contractor'), ('person', 'Name'), ('job_title', 'Job Title')], max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['option_type', 'name'],
                'unique_together': {('option_type', 'name')},
            },
        ),
    ]
