# Generated by Django 6.0.3 on 2026-03-21 10:58

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_supervisor_activity_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='photo_columns',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reports.models.report_photo_path)),
                ('caption', models.TextField(blank=True)),
                ('border_style', models.CharField(choices=[('none', 'None'), ('thin', 'Thin'), ('thick', 'Thick'), ('shadow', 'Shadow')], default='none', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.dailyreport')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
