# Generated by Django 6.0.3 on 2026-03-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_dailyreport_photo_columns_reportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='show_map_overlay',
            field=models.BooleanField(default=False),
        ),
    ]
