# Generated by Django 6.0.3 on 2026-03-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_job_show_map_overlay'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyManagementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departing_from', models.CharField(blank=True, max_length=200)),
                ('depart_date', models.DateField(blank=True, null=True)),
                ('depart_time', models.TimeField(blank=True, null=True)),
                ('depart_contact', models.CharField(blank=True, max_length=100)),
                ('depart_phone', models.CharField(blank=True, max_length=50)),
                ('overnight_arrival_date', models.DateField(blank=True, null=True)),
                ('overnight_arrival_time', models.TimeField(blank=True, null=True)),
                ('overnight_departure_date', models.DateField(blank=True, null=True)),
                ('overnight_departure_time', models.TimeField(blank=True, null=True)),
                ('arriving_at', models.CharField(blank=True, max_length=200)),
                ('arrive_date', models.DateField(blank=True, null=True)),
                ('arrive_time', models.TimeField(blank=True, null=True)),
                ('arrive_contact', models.CharField(blank=True, max_length=100)),
                ('arrive_phone', models.CharField(blank=True, max_length=50)),
                ('route', models.TextField(blank=True)),
                ('break_journey_at', models.TextField(blank=True)),
                ('radio_channel', models.CharField(blank=True, max_length=50)),
                ('other_instructions', models.TextField(blank=True)),
                ('coordinator_name', models.CharField(blank=True, max_length=100)),
                ('coordinator_phone', models.CharField(blank=True, max_length=50)),
                ('plan_communicated', models.BooleanField(blank=True, null=True)),
                ('before_signature', models.CharField(blank=True, max_length=100)),
                ('before_date', models.DateField(blank=True, null=True)),
                ('journey_completed', models.BooleanField(blank=True, null=True)),
                ('after_signature', models.CharField(blank=True, max_length=100)),
                ('after_date', models.DateField(blank=True, null=True)),
                ('action_items', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_plans', to='reports.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_driver', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='reports.journeymanagementplan')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
