# Generated by Django 6.0.3 on 2026-03-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0041_journeymanagementplan_journeypersonnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('daily', 'Daily Toolbox Meeting'), ('jmp', 'Journey Management Toolbox')], default='daily', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('days_on_job', models.CharField(blank=True, max_length=20)),
                ('jmp_number', models.CharField(blank=True, max_length=50)),
                ('yesterday_activities', models.TextField(blank=True)),
                ('jmp_route_discussed', models.BooleanField(default=False)),
                ('jmp_hours_noted', models.BooleanField(default=False)),
                ('jmp_contact_numbers', models.BooleanField(default=False)),
                ('jmp_signed_off', models.BooleanField(default=False)),
                ('jmp_lead_tail', models.BooleanField(default=False)),
                ('todays_activities', models.TextField(blank=True)),
                ('terrain_discussion', models.TextField(blank=True)),
                ('road_condition', models.TextField(blank=True)),
                ('muster_point', models.CharField(blank=True, max_length=200)),
                ('forecast', models.TextField(blank=True)),
                ('uv_index', models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('extreme', 'Extreme')], max_length=10)),
                ('chance_of_rain', models.CharField(blank=True, max_length=50)),
                ('min_temp', models.CharField(blank=True, max_length=20)),
                ('max_temp', models.CharField(blank=True, max_length=20)),
                ('grass_fire', models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('extreme', 'Extreme')], max_length=10)),
                ('forest_fire', models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('extreme', 'Extreme')], max_length=10)),
                ('wind', models.CharField(blank=True, max_length=100)),
                ('other_topics', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_meetings', to='reports.job')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolboxAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('bac', models.CharField(blank=True, max_length=20)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='reports.toolboxmeeting')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
