# Generated by Django 6.0.3 on 2026-03-22 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_job_skill_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPersonnelRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('job_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='reports.jobpersonnel')),
            ],
            options={
                'ordering': ['role'],
                'unique_together': {('job_personnel', 'role')},
            },
        ),
    ]
