# Generated by Django 6.0.3 on 2026-03-22 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0044_job_personnel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('job_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='reports.jobpersonnel')),
            ],
            options={
                'unique_together': {('job_personnel', 'date')},
            },
        ),
    ]
