# Generated by Django 6.0.3 on 2026-03-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0045_personnel_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#4caf50', max_length=7)),
                ('pattern', models.CharField(choices=[('solid', 'Solid'), ('stripes', 'Stripes'), ('dots', 'Dots'), ('cross', 'Cross-hatch')], default='solid', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
