# Generated by Django 6.0.3 on 2026-03-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0047_job_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMusterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_muster_points', to='reports.job')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('job', 'name')},
            },
        ),
    ]
