# Generated by Django 6.0.3 on 2026-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0049_toolbox_topic_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeypersonnel',
            name='rego',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
