# Generated by Django 6.0.3 on 2026-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_journey_personnel_rego'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeymanagementplan',
            name='overnight_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
