# Generated by Django 6.0.3 on 2026-03-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0051_journey_overnight_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeymanagementplan',
            name='max_rest_interval',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
