# Generated by Django 6.0.3 on 2026-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0052_journey_max_rest_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeymanagementplan',
            name='max_rest_interval',
        ),
        migrations.AddField(
            model_name='journeymanagementplan',
            name='rest_stops_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journeymanagementplan',
            name='route_waypoints',
            field=models.TextField(blank=True),
        ),
    ]
