# Generated by Django 6.0.3 on 2026-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0065_alloc_tabs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpersonnel',
            options={'ordering': ['sort_order', 'role', 'name']},
        ),
        migrations.AddField(
            model_name='personnelscheduleentry',
            name='note',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='jobfieldoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
