# Generated by Django 6.0.3 on 2026-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0066_add_schedule_entry_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolboxattendee',
            name='job_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='toolboxattendee',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
