# Generated by Django 6.0.3 on 2026-03-24 09:00

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0067_add_attendee_role_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reports.models.toolbox_photo_path)),
                ('caption', models.TextField(blank=True)),
                ('border_style', models.CharField(choices=[('none', 'None'), ('thin', 'Thin'), ('thick', 'Thick'), ('shadow', 'Shadow')], default='none', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.toolboxmeeting')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
