# Generated by Django 6.0.3 on 2026-03-24 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0069_toolboxmeeting_photo_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='take5_pin',
            field=models.CharField(blank=True, max_length=20, verbose_name='Take 5 PIN'),
        ),
        migrations.CreateModel(
            name='Take5Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('task_description', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take5_records', to='reports.job')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Take5Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.CharField(max_length=300)),
                ('control', models.CharField(max_length=300)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='reports.take5record')),
            ],
        ),
    ]
