# Generated by Django 6.0.3 on 2026-03-24 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0070_add_take5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='take5hazard',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.RemoveField(
            model_name='take5hazard',
            name='control',
        ),
        migrations.AddField(
            model_name='take5hazard',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Take5Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='reports.take5hazard')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
