# Generated by Django 6.0.3 on 2026-03-26 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0076_journey_map_tile_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreJobVibFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pre_job_vib/')),
                ('original_name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_job_vib_files', to='reports.job')),
            ],
        ),
    ]
