# Generated by Django 6.0.3 on 2026-03-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0077_prejobvibfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMegaBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DeadNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('battery', 'Battery Failure'), ('physical', 'Physical Damage'), ('lost', 'Lost'), ('firmware', 'Firmware / Software Issue'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('reported_by', models.CharField(blank=True, max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_nodes', to='reports.job')),
            ],
            options={
                'ordering': ['-date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='NodeCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mega_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crates', to='reports.nodemegabin')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='NodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('crate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='reports.nodecrate')),
            ],
            options={
                'ordering': ['scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeStockTakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('pre_job', 'Pre-Job'), ('post_job', 'Post-Job')], default='pre_job', max_length=10)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_stock_takes', to='reports.job')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='nodemegabin',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mega_bins', to='reports.nodestocktakesession'),
        ),
    ]
