# Generated by Django 6.0.3 on 2026-03-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0078_nodemegabin_deadnode_nodecrate_noderecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodestocktakesession',
            name='crates_per_mega_bin',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='nodestocktakesession',
            name='nodes_per_crate',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
