# Generated by Django 6.0.3 on 2026-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0079_nodestocktakesession_crates_per_mega_bin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noderecord',
            options={'ordering': ['slot']},
        ),
        migrations.AddField(
            model_name='noderecord',
            name='slot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='noderecord',
            unique_together={('crate', 'slot')},
        ),
    ]
