# Generated by Django 6.0.3 on 2026-03-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0080_alter_noderecord_options_noderecord_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodestocktakesession',
            name='crate_columns',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
