# Generated by Django 6.0.3 on 2026-03-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0081_nodestocktakesession_crate_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodestocktakesession',
            name='watch_color',
            field=models.CharField(default='#ff8800', max_length=20),
        ),
        migrations.AddField(
            model_name='nodestocktakesession',
            name='watch_serials',
            field=models.TextField(blank=True),
        ),
    ]
