# Generated by Django 6.0.3 on 2026-03-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0089_jsa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpersonnel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='journeypersonnel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='journeyv2personnel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='toolboxattendee',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='job',
            name='include_signatures',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infieldaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jsa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tasksafetyobservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
