# Generated by Django 6.0.3 on 2026-04-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0091_equipment_serial_number_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolboxattendee',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AddField(
            model_name='toolboxattendee',
            name='is_separator',
            field=models.BooleanField(default=False),
        ),
    ]
