# Generated by Django 6.0.3 on 2026-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0092_toolboxattendee_add_is_separator'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rps_file',
            field=models.FileField(blank=True, null=True, upload_to='survey_positions/', verbose_name='RPS File'),
        ),
        migrations.AddField(
            model_name='job',
            name='sps_file',
            field=models.FileField(blank=True, null=True, upload_to='survey_positions/', verbose_name='SPS File'),
        ),
    ]
