# Generated by Django 6.0.3 on 2026-04-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0098_line_stats_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='node_stats_override',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
