# Generated by Django 6.0.3 on 2026-04-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0099_node_stats_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='pdf_deploy_mode',
            field=models.CharField(default='alldays', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='pdf_map_views',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
